build:
  nodes:
    analysis:
      dependencies:
        before:
        - sudo apt-get install -y autoconf g++ make openssl libssl-dev libcurl4-openssl-dev
        - sudo apt-get install -y libevent-dev libsslcommon2-dev
        - sudo apt-get install -y libcurl4-openssl-dev pkg-config
        - sudo apt-get install -y libsasl2-dev
      tests:
        override:
        - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
        - command: 'php ./vendor/bin/phpunit --coverage-clover=clover.xml'
          coverage:
            file: clover.xml
            format: clover