build:
  nodes:
    analysis:
      tests:
        dependencies:
          before:
          - sudo apt-get install -y libevent-dev
        override:
        - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
        - command: 'php ./vendor/bin/phpunit --coverage-clover=clover.xml'
          coverage:
            file: clover.xml
            format: clover