language: php

php:
- 7.2
- 7.3
- nightly

matrix:
  allow_failures:
  - php: 7.3
  - php: nightly

addons:
  apt:
    packages:
    - libevent-dev

cache:
  bundler: true

install:
  - travis_retry ./bin/travis/travis-init.sh
  - travis_retry composer install --no-interaction --prefer-source

script:
  vendor/bin/phpunit --coverage-text