<?php
/**
 * User: alec
 * Date: 06.11.18
 * Time: 14:06
 */

namespace AlecRabbit\Assets\Subclasses;

use AlecRabbit\Assets\Asset;
use AlecRabbit\Currency\Currency;

/**
 * This is a generated file. Do not edit it manually!
 *
 * @method static Asset AED(string $amount)
 * @method static Asset ALL(string $amount)
 * @method static Asset AMD(string $amount)
 * @method static Asset ANG(string $amount)
 * @method static Asset AOA(string $amount)
 * @method static Asset ARS(string $amount)
 * @method static Asset AUD(string $amount)
 * @method static Asset AWG(string $amount)
 * @method static Asset AZN(string $amount)
 * @method static Asset BAM(string $amount)
 * @method static Asset BBD(string $amount)
 * @method static Asset BDT(string $amount)
 * @method static Asset BGN(string $amount)
 * @method static Asset BHD(string $amount)
 * @method static Asset BIF(string $amount)
 * @method static Asset BMD(string $amount)
 * @method static Asset BND(string $amount)
 * @method static Asset BOB(string $amount)
 * @method static Asset BOV(string $amount)
 * @method static Asset BRL(string $amount)
 * @method static Asset BSD(string $amount)
 * @method static Asset BTN(string $amount)
 * @method static Asset BWP(string $amount)
 * @method static Asset BYN(string $amount)
 * @method static Asset BZD(string $amount)
 * @method static Asset CAD(string $amount)
 * @method static Asset CDF(string $amount)
 * @method static Asset CHE(string $amount)
 * @method static Asset CHF(string $amount)
 * @method static Asset CHW(string $amount)
 * @method static Asset CLF(string $amount)
 * @method static Asset CLP(string $amount)
 * @method static Asset CNY(string $amount)
 * @method static Asset COP(string $amount)
 * @method static Asset COU(string $amount)
 * @method static Asset CRC(string $amount)
 * @method static Asset CUC(string $amount)
 * @method static Asset CUP(string $amount)
 * @method static Asset CVE(string $amount)
 * @method static Asset CZK(string $amount)
 * @method static Asset DJF(string $amount)
 * @method static Asset DKK(string $amount)
 * @method static Asset DOP(string $amount)
 * @method static Asset DZD(string $amount)
 * @method static Asset EGP(string $amount)
 * @method static Asset ERN(string $amount)
 * @method static Asset ETB(string $amount)
 * @method static Asset EUR(string $amount)
 * @method static Asset FJD(string $amount)
 * @method static Asset FKP(string $amount)
 * @method static Asset GBP(string $amount)
 * @method static Asset GEL(string $amount)
 * @method static Asset GHS(string $amount)
 * @method static Asset GIP(string $amount)
 * @method static Asset GMD(string $amount)
 * @method static Asset GNF(string $amount)
 * @method static Asset GTQ(string $amount)
 * @method static Asset GYD(string $amount)
 * @method static Asset HKD(string $amount)
 * @method static Asset HNL(string $amount)
 * @method static Asset HRK(string $amount)
 * @method static Asset HTG(string $amount)
 * @method static Asset HUF(string $amount)
 * @method static Asset IDR(string $amount)
 * @method static Asset ILS(string $amount)
 * @method static Asset INR(string $amount)
 * @method static Asset IQD(string $amount)
 * @method static Asset IRR(string $amount)
 * @method static Asset ISK(string $amount)
 * @method static Asset JMD(string $amount)
 * @method static Asset JOD(string $amount)
 * @method static Asset JPY(string $amount)
 * @method static Asset KES(string $amount)
 * @method static Asset KGS(string $amount)
 * @method static Asset KHR(string $amount)
 * @method static Asset KMF(string $amount)
 * @method static Asset KPW(string $amount)
 * @method static Asset KRW(string $amount)
 * @method static Asset KWD(string $amount)
 * @method static Asset KYD(string $amount)
 * @method static Asset KZT(string $amount)
 * @method static Asset LAK(string $amount)
 * @method static Asset LBP(string $amount)
 * @method static Asset LKR(string $amount)
 * @method static Asset LRD(string $amount)
 * @method static Asset LSL(string $amount)
 * @method static Asset LYD(string $amount)
 * @method static Asset MAD(string $amount)
 * @method static Asset MDL(string $amount)
 * @method static Asset MGA(string $amount)
 * @method static Asset MKD(string $amount)
 * @method static Asset MMK(string $amount)
 * @method static Asset MNT(string $amount)
 * @method static Asset MOP(string $amount)
 * @method static Asset MRU(string $amount)
 * @method static Asset MUR(string $amount)
 * @method static Asset MVR(string $amount)
 * @method static Asset MWK(string $amount)
 * @method static Asset MXN(string $amount)
 * @method static Asset MXV(string $amount)
 * @method static Asset MYR(string $amount)
 * @method static Asset MZN(string $amount)
 * @method static Asset NAD(string $amount)
 * @method static Asset NGN(string $amount)
 * @method static Asset NIO(string $amount)
 * @method static Asset NOK(string $amount)
 * @method static Asset NPR(string $amount)
 * @method static Asset NZD(string $amount)
 * @method static Asset OMR(string $amount)
 * @method static Asset PAB(string $amount)
 * @method static Asset PEN(string $amount)
 * @method static Asset PGK(string $amount)
 * @method static Asset PHP(string $amount)
 * @method static Asset PKR(string $amount)
 * @method static Asset PLN(string $amount)
 * @method static Asset PYG(string $amount)
 * @method static Asset QAR(string $amount)
 * @method static Asset RON(string $amount)
 * @method static Asset RSD(string $amount)
 * @method static Asset RUB(string $amount)
 * @method static Asset RWF(string $amount)
 * @method static Asset SAR(string $amount)
 * @method static Asset SBD(string $amount)
 * @method static Asset SCR(string $amount)
 * @method static Asset SDG(string $amount)
 * @method static Asset SEK(string $amount)
 * @method static Asset SGD(string $amount)
 * @method static Asset SHP(string $amount)
 * @method static Asset SLL(string $amount)
 * @method static Asset SOS(string $amount)
 * @method static Asset SRD(string $amount)
 * @method static Asset SSP(string $amount)
 * @method static Asset STN(string $amount)
 * @method static Asset SVC(string $amount)
 * @method static Asset SYP(string $amount)
 * @method static Asset SZL(string $amount)
 * @method static Asset THB(string $amount)
 * @method static Asset TJS(string $amount)
 * @method static Asset TMT(string $amount)
 * @method static Asset TND(string $amount)
 * @method static Asset TOP(string $amount)
 * @method static Asset TRY(string $amount)
 * @method static Asset TTD(string $amount)
 * @method static Asset TWD(string $amount)
 * @method static Asset TZS(string $amount)
 * @method static Asset UAH(string $amount)
 * @method static Asset UGX(string $amount)
 * @method static Asset USD(string $amount)
 * @method static Asset USN(string $amount)
 * @method static Asset UYI(string $amount)
 * @method static Asset UYU(string $amount)
 * @method static Asset UZS(string $amount)
 * @method static Asset VEF(string $amount)
 * @method static Asset VND(string $amount)
 * @method static Asset VUV(string $amount)
 * @method static Asset WST(string $amount)
 * @method static Asset XAF(string $amount)
 * @method static Asset XAG(string $amount)
 * @method static Asset XAU(string $amount)
 * @method static Asset XBA(string $amount)
 * @method static Asset XBB(string $amount)
 * @method static Asset XBC(string $amount)
 * @method static Asset XBD(string $amount)
 * @method static Asset XBT(string $amount)
 * @method static Asset XCD(string $amount)
 * @method static Asset XDR(string $amount)
 * @method static Asset XOF(string $amount)
 * @method static Asset XPD(string $amount)
 * @method static Asset XPF(string $amount)
 * @method static Asset XPT(string $amount)
 * @method static Asset XSU(string $amount)
 * @method static Asset XTS(string $amount)
 * @method static Asset XUA(string $amount)
 * @method static Asset XXX(string $amount)
 * @method static Asset YER(string $amount)
 * @method static Asset ZAR(string $amount)
 * @method static Asset ZMW(string $amount)
 * @method static Asset ZWL(string $amount)
 */
trait AssetFactory
{
    /**
     * Convenience factory method for a Money object.
     *
     * <code>
     * $fiveDollar = Money::USD(500);
     * </code>
     *
     * @param string $method
     * @param array  $arguments
     *
     * @return Asset
     *
     * @throws \InvalidArgumentException If amount is not integer(ish)
     */
    public static function __callStatic($method, $arguments)
    {
        return new Asset($arguments[0], new Currency($method));
    }
}
